spring.application.name=training-service
server.port=8081
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/training_db
spring.datasource.username=Arm
spring.datasource.password=1234

#Kafka initial config
spring.kafka.producer.bootstrap-servers=localhost:9092

#Kafka Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

#Kafka Consumer Configuration
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.demo.response
#spring.kafka.consumer.properties.spring.deserialization.fail-on-unknown-properties=false
#spring.kafka.consumer.properties.spring.deserialization.fail-on-missing-type-header=false
#spring.kafka.consumer.properties.spring.json.use.type.headers=false
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.group-id=disable-consumer-groups

#JWT and Security
jwt.secret=super_secret_key_123456_super_secret_key
jwt.expirationMs=86400000


#EurekaService
#eureka.client.service-url.defaultZone: http://localhost:8755/eureka
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=true
#eureka.instance.hostname=localhost
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
